print("Welcome to the Tip Calculator!!")
bill = float(input("What was the total bill?\n"))
tip = int(input("How much of a tip would you like to give? 15, 20, 25?\n"))
num_of_people = int(input("How many people are splitting the bill?\n"))
tip_amount = float(tip / 100 * bill)
amount_to_pay = round(((bill + tip_amount)/ num_of_people), 2)
print(f"Each person should pay ${amount_to_pay}")